title : Jekyll API

safe: true
lsi: false
pygments: true
auto: true

source: jekyll-api
destination: jekyll-api

permalink: /:categories
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

production_url : http://kinlane.github.io/jekyll-api/

