title : Dev Hub

safe: true
lsi: false
pygments: true
auto: true

source: dev-hub
destination: dev-hub

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

production_url : http://kinlane.github.io/dev-hub/

BASE_PATH : http://kinlane.github.io/dev-hub/

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
